# Generated by Django 5.2.17 on 2026-09-08 18:37

import apps.comum.validators
import apps.contas.models
import apps.contas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="e-mail")),
                ("nome_completo", models.CharField(max_length=200, verbose_name="nome completo")),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[apps.contas.validators.valida_cpf],
                        verbose_name="CPF",
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20, verbose_name="telefone")),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        upload_to="fotos/",
                        validators=[
                            apps.comum.validators.valida_extensao_imagem,
                            apps.comum.validators.valida_tamanho_arquivo,
                        ],
                        verbose_name="foto",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("ALUNO", "Aluno"),
                            ("PROFESSOR", "Professor"),
                            ("SUGRAD", "SUGRAD"),
                        ],
                        default="PROFESSOR",
                        max_length=10,
                        verbose_name="papel",
                    ),
                ),
                (
                    "is_coordenador",
                    models.BooleanField(default=False, verbose_name="é coordenador"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                ("is_staff", models.BooleanField(default=False, verbose_name="acessa o admin")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
                "ordering": ["nome_completo"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("papel", "SUGRAD"), ("cpf__isnull", False), _connector="OR"
                        ),
                        name="cpf_obrigatorio_para_pessoas",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("papel", "SUGRAD")),
                        fields=("papel",),
                        name="conta_sugrad_unica",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_coordenador", False), ("papel", "PROFESSOR"), _connector="OR"
                        ),
                        name="coordenador_e_professor",
                    ),
                ],
            },
            managers=[
                ("objects", apps.contas.models.GerenciadorUsuario()),
            ],
        ),
    ]
