# Generated by Django 5.2.17 on 2026-09-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usuario",
            name="cpf_obrigatorio_para_pessoas",
        ),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("papel", "SUGRAD"),
                    models.Q(("cpf__isnull", False), models.Q(("cpf", ""), _negated=True)),
                    _connector="OR",
                ),
                name="cpf_obrigatorio_para_pessoas",
            ),
        ),
    ]
