# Generated by Django 5.2.17 on 2026-09-09 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_fortalece_cpf_obrigatorio_para_pessoas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True, verbose_name="nome")),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
            ],
            options={
                "verbose_name": "área",
                "verbose_name_plural": "áreas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PerfilAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "matricula",
                    models.CharField(max_length=20, unique=True, verbose_name="matrícula"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_aluno",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de aluno",
                "verbose_name_plural": "perfis de alunos",
            },
        ),
        migrations.CreateModel(
            name="PerfilProfessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("siape", models.CharField(max_length=20, unique=True, verbose_name="SIAPE")),
                (
                    "areas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="professores",
                        to="contas.area",
                        verbose_name="áreas de atuação",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_professor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de professor",
                "verbose_name_plural": "perfis de professores",
            },
        ),
    ]
