# Generated by Django 5.2.17 on 2026-09-09 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0003_area_perfilaluno_perfilprofessor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Convite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                (
                    "papel",
                    models.CharField(
                        choices=[("ALUNO", "Aluno"), ("PROFESSOR", "Professor")],
                        max_length=10,
                        verbose_name="papel",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(max_length=64, unique=True, verbose_name="hash do token"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("expira_em", models.DateTimeField(verbose_name="expira em")),
                ("usado_em", models.DateTimeField(blank=True, null=True, verbose_name="usado em")),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convites_enviados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "usuario_criado",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="convite_de_origem",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário criado",
                    ),
                ),
            ],
            options={
                "verbose_name": "convite",
                "verbose_name_plural": "convites",
                "ordering": ["-criado_em"],
            },
        ),
    ]
