# Generated by Django 5.2.17 on 2026-09-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0004_convite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convite",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, verbose_name="e-mail"),
        ),
    ]
