# Generated by Django 5.2.17 on 2026-09-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0005_alter_convite_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["ordem", "nome"],
                "verbose_name": "área",
                "verbose_name_plural": "áreas",
            },
        ),
        migrations.AddField(
            model_name="area",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Área à qual esta subárea pertence (vazio para uma área em si).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subareas",
                to="contas.area",
                verbose_name="área",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="ordem",
            field=models.PositiveSmallIntegerField(default=1000, verbose_name="ordem de exibição"),
        ),
    ]
