# Generated by Django 5.2.17 on 2026-09-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0005_alter_convite_email"),
        ("projetos", "0004_remove_projeto_projeto_ativo_unico_por_aluno_e_etapa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data_hora", models.DateTimeField(verbose_name="data e hora")),
                ("local", models.CharField(max_length=200, verbose_name="local")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADA", "Agendada"),
                            ("REALIZADA", "Realizada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="AGENDADA",
                        max_length=9,
                        verbose_name="status",
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True, verbose_name="nota"
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APROVADO_COM_RESSALVAS", "Aprovado com ressalvas"),
                            ("REPROVADO", "Reprovado"),
                        ],
                        default="",
                        max_length=22,
                        verbose_name="resultado",
                    ),
                ),
                ("comentario", models.TextField(blank=True, default="", verbose_name="comentário")),
                ("criada_em", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bancas",
                        to="projetos.projeto",
                        verbose_name="projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "banca",
                "verbose_name_plural": "bancas",
                "ordering": ["-criada_em"],
            },
        ),
        migrations.CreateModel(
            name="MembroBanca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nome_externo",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="nome (externo)"
                    ),
                ),
                (
                    "banca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="bancas.banca",
                        verbose_name="banca",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participacoes_em_banca",
                        to="contas.perfilprofessor",
                        verbose_name="professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "membro da banca",
                "verbose_name_plural": "membros da banca",
            },
        ),
        migrations.AddConstraint(
            model_name="banca",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELADA"), _negated=True),
                fields=("projeto",),
                name="banca_ativa_unica_por_projeto",
            ),
        ),
        migrations.AddConstraint(
            model_name="membrobanca",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("nome_externo", ""), ("professor__isnull", False)),
                    models.Q(
                        ("professor__isnull", True), models.Q(("nome_externo", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="membro_banca_interno_xor_externo",
            ),
        ),
    ]
