# Generated by Django 5.2.17 on 2026-09-14 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bancas", "0001_initial"),
        ("projetos", "0004_remove_projeto_projeto_ativo_unico_por_aluno_e_etapa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCorrecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="descrição")),
                ("concluido", models.BooleanField(default=False, verbose_name="concluído")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_correcao",
                        to="projetos.projeto",
                        verbose_name="projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "item de correção",
                "verbose_name_plural": "itens de correção",
                "ordering": ["criado_em"],
            },
        ),
    ]
