# Generated by Django 5.2.17 on 2026-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bancas", "0002_itemcorrecao"),
        ("projetos", "0006_remove_tema_area_tema_areas"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="banca",
            name="banca_ativa_unica_por_projeto",
        ),
        migrations.AddConstraint(
            model_name="banca",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "AGENDADA")),
                fields=("projeto",),
                name="banca_ativa_unica_por_projeto",
            ),
        ),
    ]
