# Generated by Django 5.2.17 on 2026-09-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bancas", "0003_corrige_banca_ativa_unica_por_projeto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banca",
            name="resultado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APROVADO_COM_RESSALVAS", "Aprovado com ressalvas"),
                    ("REPROVADO", "Reprovado"),
                ],
                default="",
                max_length=32,
                verbose_name="resultado",
            ),
        ),
    ]
