# Generated by Django 5.2.17 on 2026-09-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bancas", "0001_initial"),
        ("projetos", "0004_remove_projeto_projeto_ativo_unico_por_aluno_e_etapa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero", models.CharField(max_length=20, verbose_name="número")),
                ("pdf", models.FileField(upload_to="atas/", verbose_name="PDF")),
                ("gerada_em", models.DateTimeField(auto_now_add=True, verbose_name="gerada em")),
                (
                    "banca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atas",
                        to="bancas.banca",
                        verbose_name="banca",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atas",
                        to="projetos.projeto",
                        verbose_name="projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "ata",
                "verbose_name_plural": "atas",
                "ordering": ["-gerada_em"],
            },
        ),
        migrations.CreateModel(
            name="RevisaoSUGRAD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADA", "Aprovada"),
                            ("DEVOLVIDA", "Devolvida"),
                        ],
                        default="PENDENTE",
                        max_length=9,
                        verbose_name="status",
                    ),
                ),
                ("comentario", models.TextField(blank=True, default="", verbose_name="comentário")),
                (
                    "decidida_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="decidida em"),
                ),
                (
                    "ata",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisao",
                        to="documentos.ata",
                        verbose_name="ata",
                    ),
                ),
            ],
            options={
                "verbose_name": "revisão da SUGRAD",
                "verbose_name_plural": "revisões da SUGRAD",
            },
        ),
    ]
