# Generated by Django 5.2.17 on 2026-09-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ata",
            name="numero",
            field=models.CharField(max_length=20, unique=True, verbose_name="número"),
        ),
    ]
