# Generated by Django 5.2.17 on 2026-09-10 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0005_alter_convite_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("descricao", models.TextField(verbose_name="descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="temas",
                        to="contas.area",
                        verbose_name="área",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="temas",
                        to="contas.perfilprofessor",
                        verbose_name="professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "tema",
                "verbose_name_plural": "temas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LimiteOrientacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[("TCC_I", "TCC I"), ("TCC_II", "TCC II")],
                        max_length=6,
                        verbose_name="etapa",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="ano")),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1º"), (2, "2º")], verbose_name="período"
                    ),
                ),
                ("limite", models.PositiveSmallIntegerField(verbose_name="limite")),
                ("justificativa", models.TextField(verbose_name="justificativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="limites_concedidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autorizado por",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="limites_de_orientacao",
                        to="contas.perfilprofessor",
                        verbose_name="professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "limite de orientação",
                "verbose_name_plural": "limites de orientação",
                "ordering": ["-criado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("professor", "etapa", "ano", "periodo"),
                        name="limite_unico_por_professor_etapa_e_semestre",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("limite__gt", 3)), name="limite_maior_que_padrao"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[("TCC_I", "TCC I"), ("TCC_II", "TCC II")],
                        max_length=6,
                        verbose_name="etapa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("AGUARDANDO_DEFESA", "Aguardando defesa"),
                            ("APROVADO_COM_RESSALVAS", "Aprovado com ressalvas"),
                            ("APROVADO", "Aprovado"),
                            ("CONCLUIDO", "Concluído"),
                            ("REPROVADO", "Reprovado"),
                        ],
                        default="EM_ANDAMENTO",
                        max_length=22,
                        verbose_name="status",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="ano")),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1º"), (2, "2º")], verbose_name="período"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projetos_como_aluno",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aluno",
                    ),
                ),
                (
                    "orientador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projetos_orientados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="orientador",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="projetos.tema",
                        verbose_name="tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "projeto",
                "verbose_name_plural": "projetos",
                "ordering": ["-criado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["CONCLUIDO", "REPROVADO"]), _negated=True
                        ),
                        fields=("aluno", "etapa"),
                        name="projeto_ativo_unico_por_aluno_e_etapa",
                    )
                ],
            },
        ),
    ]
