# Generated by Django 5.2.17 on 2026-09-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0005_alter_convite_email"),
        ("projetos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_CURSO", "Em curso"),
                            ("ACEITA", "Aceita"),
                            ("ESGOTADA", "Esgotada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="EM_CURSO",
                        max_length=9,
                        verbose_name="status",
                    ),
                ),
                (
                    "opcao_atual",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Ordem (1 a 3) em que a cascata de opções está.",
                        verbose_name="opção atual",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="ano")),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1º"), (2, "2º")], verbose_name="período"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidaturas",
                        to="contas.perfilaluno",
                        verbose_name="aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidatura",
                "verbose_name_plural": "candidaturas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="OpcaoCandidatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(verbose_name="ordem")),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando"),
                            ("ENVIADA", "Enviada"),
                            ("ACEITA", "Aceita"),
                            ("RECUSADA", "Recusada"),
                            ("EXPIRADA", "Expirada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="AGUARDANDO",
                        max_length=10,
                        verbose_name="situação",
                    ),
                ),
                (
                    "enviada_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="enviada em"),
                ),
                ("prazo", models.DateTimeField(blank=True, null=True, verbose_name="prazo")),
                (
                    "respondida_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="respondida em"),
                ),
                ("justificativa", models.TextField(blank=True, verbose_name="justificativa")),
                (
                    "candidatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opcoes",
                        to="projetos.candidatura",
                        verbose_name="candidatura",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opcoes_recebidas",
                        to="contas.perfilprofessor",
                        verbose_name="professor",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opcoes",
                        to="projetos.tema",
                        verbose_name="tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "opção de candidatura",
                "verbose_name_plural": "opções de candidatura",
                "ordering": ["candidatura", "ordem"],
            },
        ),
        migrations.AddConstraint(
            model_name="candidatura",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "EM_CURSO")),
                fields=("aluno",),
                name="candidatura_em_curso_unica_por_aluno",
            ),
        ),
        migrations.AddConstraint(
            model_name="opcaocandidatura",
            constraint=models.UniqueConstraint(
                fields=("candidatura", "ordem"), name="opcao_ordem_unica_por_candidatura"
            ),
        ),
        migrations.AddConstraint(
            model_name="opcaocandidatura",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordem__gte", 1), ("ordem__lte", 3)),
                name="opcao_ordem_entre_um_e_tres",
            ),
        ),
        # Trava 4 (spec §4.3): "tema nulo, ou tema cujo professor é o mesmo da
        # opção". Não é um AddConstraint porque um CheckConstraint do Postgres
        # não pode consultar outra tabela — Q(tema__professor=F("professor"))
        # levanta django.core.exceptions.FieldError ("Joined field references
        # are not permitted in this query") ao tentar aplicar a migração
        # (verificado manualmente: apps/projetos/models.py tem o traço dessa
        # checagem no comentário de OpcaoCandidatura.Meta). A trigger abaixo é
        # a forma de obter, mesmo assim, um IntegrityError real por linha,
        # sem alterar a tabela de Tema (fora do escopo desta tarefa).
        #
        # A trigger só compara quando NEW.tema_id IS NOT NULL: uma opção com
        # tema nulo nunca aciona a comparação — exatamente o caso válido
        # "aberto a temas".
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION projetos_valida_tema_do_professor_da_opcao()
                RETURNS trigger AS $$
                BEGIN
                    IF NEW.tema_id IS NOT NULL AND NEW.professor_id != (
                        SELECT professor_id FROM projetos_tema WHERE id = NEW.tema_id
                    ) THEN
                        RAISE EXCEPTION
                            'opcao_tema_do_mesmo_professor: o tema da opção % '
                            'não pertence ao professor % da própria opção',
                            NEW.tema_id, NEW.professor_id
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER valida_tema_do_professor_da_opcao
                    BEFORE INSERT OR UPDATE ON projetos_opcaocandidatura
                    FOR EACH ROW
                    EXECUTE FUNCTION projetos_valida_tema_do_professor_da_opcao();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS valida_tema_do_professor_da_opcao
                    ON projetos_opcaocandidatura;
                DROP FUNCTION IF EXISTS projetos_valida_tema_do_professor_da_opcao();
            """,
        ),
    ]
