# Generated by Django 5.2.17 on 2026-09-14 13:22

import apps.comum.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0002_candidatura_opcaocandidatura"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submissao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        upload_to="submissoes/",
                        validators=[
                            apps.comum.validators.valida_extensao_pdf,
                            apps.comum.validators.valida_tamanho_arquivo,
                        ],
                        verbose_name="PDF",
                    ),
                ),
                (
                    "editavel",
                    models.FileField(
                        upload_to="submissoes/",
                        validators=[
                            apps.comum.validators.valida_extensao_editavel,
                            apps.comum.validators.valida_tamanho_arquivo,
                        ],
                        verbose_name="editável",
                    ),
                ),
                ("versao", models.PositiveSmallIntegerField(default=1, verbose_name="versão")),
                ("enviada_em", models.DateTimeField(auto_now_add=True, verbose_name="enviada em")),
                (
                    "atualizada_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "projeto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissao",
                        to="projetos.projeto",
                        verbose_name="projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "submissão",
                "verbose_name_plural": "submissões",
            },
        ),
    ]
