# Generated by Django 5.2.17 on 2026-09-14 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0003_submissao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projeto",
            name="projeto_ativo_unico_por_aluno_e_etapa",
        ),
        migrations.AlterField(
            model_name="projeto",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_ANDAMENTO", "Em andamento"),
                    ("AGUARDANDO_DEFESA", "Aguardando defesa"),
                    ("APROVADO_COM_RESSALVAS", "Aprovado com ressalvas"),
                    ("APROVADO", "Aprovado"),
                    ("CONCLUIDO", "Concluído"),
                    ("REPROVADO", "Reprovado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="EM_ANDAMENTO",
                max_length=22,
                verbose_name="status",
            ),
        ),
        migrations.AddConstraint(
            model_name="projeto",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["CONCLUIDO", "REPROVADO", "CANCELADO"]), _negated=True
                ),
                fields=("aluno", "etapa"),
                name="projeto_ativo_unico_por_aluno_e_etapa",
            ),
        ),
    ]
