# Generated by Django 5.2.17 on 2026-09-14 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0005_alter_convite_email"),
        ("projetos", "0004_remove_projeto_projeto_ativo_unico_por_aluno_e_etapa_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TermoPublicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "assinado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="assinado em"),
                ),
            ],
            options={
                "verbose_name": "termo de publicação",
                "verbose_name_plural": "termos de publicação",
            },
        ),
        migrations.AddField(
            model_name="projeto",
            name="anterior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proximos",
                to="projetos.projeto",
                verbose_name="projeto anterior",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="coorientador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projetos_como_coorientador",
                to="contas.perfilprofessor",
                verbose_name="coorientador",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="coorientador_externo",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="coorientador (externo)"
            ),
        ),
        migrations.AddConstraint(
            model_name="projeto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("coorientador__isnull", True), ("coorientador_externo", "")),
                    models.Q(("coorientador__isnull", False), ("coorientador_externo", "")),
                    models.Q(
                        ("coorientador__isnull", True),
                        models.Q(("coorientador_externo", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="projeto_coorientador_nao_duplo",
            ),
        ),
        migrations.AddField(
            model_name="termopublicacao",
            name="projeto",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="termo_publicacao",
                to="projetos.projeto",
                verbose_name="projeto",
            ),
        ),
    ]
