# Generated by Django 5.2.17 on 2026-09-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0007_seed_areas_cnpq_capes"),
        ("projetos", "0005_termopublicacao_projeto_anterior_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tema",
            name="area",
        ),
        migrations.AddField(
            model_name="tema",
            name="areas",
            field=models.ManyToManyField(
                related_name="temas", to="contas.area", verbose_name="áreas"
            ),
        ),
    ]
