# Generated by Django 5.2.17 on 2026-09-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0006_remove_tema_area_tema_areas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_ANDAMENTO", "Em andamento"),
                    ("AGUARDANDO_DEFESA", "Aguardando defesa"),
                    ("APROVADO_COM_RESSALVAS", "Aprovado com ressalvas"),
                    ("APROVADO", "Aprovado"),
                    ("CONCLUIDO", "Concluído"),
                    ("REPROVADO", "Reprovado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="EM_ANDAMENTO",
                max_length=32,
                verbose_name="status",
            ),
        ),
    ]
